### ISSUE TITLE
Sources downloaded from the releases page are just crashing

### ISSUE THREAD

**Issue by IzzySoft** [ya0211/magisk-modules-repo-util#27]
If one downloads the ZIP or TAR from [`releases/`](https://github.com/ya0211/magisk-modules-repo-util/releases), all that `cli.py` will ever do is showing a stack trace:

```
Traceback (most recent call last):
  File "./cli.py", line 26, in <module>
    sys.exit(Main.exec())
  File "/mnt/data/web/ftp/repo/magisk/util/sync/cli/Main.py", line 50, in exec
    parser = Parameters.generate_parser()
  File "/mnt/data/web/ftp/repo/magisk/util/sync/cli/Parameters.py", line 76, in generate_parser
    version=str(get_version_code()),
  File "/mnt/data/web/ftp/repo/magisk/util/sync/__version__.py", line 36, in get_version_code
    count = int(GitUtils.commit_count())
  File "/mnt/data/web/ftp/repo/magisk/util/sync/utils/GitUtils.py", line 58, in commit_count
    return int(cls.exec("git rev-list --count HEAD"))
ValueError: invalid literal for int() with base 10: ''
```

It seems `cli.py` depends on the presence of the `.git/` directory just to look up how many commits there were (`git rev-list --count HEAD`) – which is not really needed to run the utility. Maybe this should be eliminated, or at least a fallback implemented. Not everyone wants to run from the latest `HEAD` (which might not be stable) – some would prefer to stick to a stable release and download it from there.

**Comment by IzzySoft** [comment]
Wow, that was fast – thanks! :star_struck:
